overblog_graphql:
    security:
        # for more flexibility use https://github.com/nelmio/NelmioCorsBundle
        handle_cors: true
    definitions:
        schema:
            query: Query
            mutation: Mutation
        mappings:
            types:
                -   type: yaml
                    dir: "%shopsys.root_dir%/config/graphql/types"
