admin_homepage:
  pattern:  /dashboard/
  defaults: { _controller: SS6AdminBundle:Default:index }
    
admin_login:
  pattern:  /
  defaults: { _controller: SS6AdminBundle:Login:login }
  
admin_login_check:
  pattern: /login_check/
    
admin_logout:
  pattern:  /logout/

admin_product_edit:
  pattern: /product/edit/{id}
  defaults: { _controller: SS6AdminBundle:Product:edit }
  requirements:
    id: \d+

admin_product_new:
  pattern: /product/new/
  defaults: { _controller: SS6AdminBundle:Product:new }
