admin_homepage:
  pattern:  /dashboard/
  defaults: { _controller: SS6AdminBundle:Default:index }
    
admin_login:
  pattern:  /
  defaults: { _controller: SS6AdminBundle:Login:login }
  
admin_login_check:
  pattern: /login_check/
    
admin_logout:
  pattern:  /logout/

admin_product_delete:
  pattern: /product/delete/{id}
  defaults: { _controller: SS6AdminBundle:Product:delete }
  requirements:
    id: \d+

admin_product_edit:
  pattern: /product/edit/{id}
  defaults: { _controller: SS6AdminBundle:Product:edit }
  requirements:
    id: \d+
    
admin_product_list:
  pattern: /product/list/
  defaults: { _controller: SS6AdminBundle:Product:list }

admin_product_new:
  pattern: /product/new/
  defaults: { _controller: SS6AdminBundle:Product:new }

admin_transport_and_payment_list:
  pattern:  /transport_and_payment/list/
  defaults: { _controller: SS6AdminBundle:TransportAndPayment:index }
