admin_homepage:
  pattern:  /dashboard/
  defaults: { _controller: SS6AdminBundle:Default:index }
    
admin_login:
  pattern:  /
  defaults: { _controller: SS6AdminBundle:Login:login }
  
admin_login_check:
  pattern: /login_check/
    
admin_logout:
  pattern:  /logout/
