services:

  shopsys.auto_services.auto_container:
    class: Shopsys\AutoServicesBundle\Compiler\AutoContainer
    arguments:
      - '@service_container'
      - '@shopsys.auto_services.service_helper'
      - '@shopsys.auto_services.container_class_list'
      - '@shopsys.auto_services.auto_services_collector'

  shopsys.auto_services.service_helper:
    class: Shopsys\AutoServicesBundle\Compiler\ServiceHelper

  shopsys.auto_services.container_class_list:
    class: Shopsys\AutoServicesBundle\Compiler\ContainerClassList
    arguments: [%kernel.cache_dir%]

  shopsys.auto_services.auto_services_collector:
    class: Shopsys\AutoServicesBundle\Compiler\AutoServicesCollector
    arguments: [%kernel.cache_dir%, %kernel.container_class%, '@filesystem']

