services:

  ss6.auto_services.auto_container:
    class: Shopsys\AutoServicesBundle\Compiler\AutoContainer
    arguments:
      - @service_container
      - @ss6.auto_services.service_helper
      - @ss6.auto_services.container_class_list
      - @ss6.auto_services.auto_services_collector

  ss6.auto_services.service_helper:
    class: Shopsys\AutoServicesBundle\Compiler\ServiceHelper

  ss6.auto_services.container_class_list:
    class: Shopsys\AutoServicesBundle\Compiler\ContainerClassList
    arguments: [%kernel.cache_dir%]

  ss6.auto_services.auto_services_collector:
    class: Shopsys\AutoServicesBundle\Compiler\AutoServicesCollector
    arguments: [%kernel.cache_dir%, %kernel.container_class%, @filesystem]

