services:
  
  ss6.twig.file_upload_extension:
    class: SS6\ShopBundle\Twig\FileUploadExtension
    tags:
      - { name: twig.extension }

  ss6.twig.form_theme_extension:
    class: SS6\ShopBundle\Twig\FormThemeExtension
    tags:
      - { name: twig.extension }
      
  ss6.twig.image_extension:
    class: SS6\ShopBundle\Twig\ImageExtension
    arguments: [%ss6.image_url_prefix%, @service_container]
    tags:
      - { name: twig.extension }
      
  ss6.twig.javascript_extension:
    class: SS6\ShopBundle\Twig\JavascriptExtension
    arguments: [%ss6.web_dir%, @service_container]
    tags:
      - { name: twig.extension }

  ss6.twig.input_price_label_extension:
    class: SS6\ShopBundle\Twig\InputPriceLabelExtension
    tags:
      - { name: twig.extension }

  ss6.twig.price_extension:
    class: SS6\ShopBundle\Twig\PriceExtension
    tags:
      - { name: twig.extension }