services:

  ss6.twig.cropzeros_extension:
    class: Shopsys\ShopBundle\Twig\CropZerosExtension
    tags:
      - { name: twig.extension }

  ss6.twig.cookies_extension:
    class: Shopsys\ShopBundle\Twig\CookiesExtension
    tags:
      - { name: twig.extension }

  ss6.twig.css_extension:
    class: Shopsys\ShopBundle\Twig\CssExtension
    tags:
      - { name: twig.extension }

  ss6.twig.date_time_formatter_extension:
    class: Shopsys\ShopBundle\Twig\DateTimeFormatterExtension
    tags:
      - { name: twig.extension }

  ss6.twig.domain_extension:
    class: Shopsys\ShopBundle\Twig\DomainExtension
    arguments:
     - %ss6.domain_images_url_prefix%
    tags:
      - { name: twig.extension }

  ss6.twig.uploaded_file_extension:
    class: Shopsys\ShopBundle\Twig\UploadedFileExtension
    tags:
      - { name: twig.extension }

  ss6.twig.file_upload_extension:
    class: Shopsys\ShopBundle\Twig\FileUploadExtension
    tags:
      - { name: twig.extension }

  ss6.shop.file.file_thumbnail_extension:
    class: Shopsys\ShopBundle\Twig\FileThumbnail\FileThumbnailExtension
    tags:
      - { name: twig.extension }

  ss6.twig.form_detail_extension:
    class: Shopsys\ShopBundle\Twig\FormDetailExtension
    tags:
      -  { name: twig.extension }

  ss6.twig.form_theme_extension:
    class: Shopsys\ShopBundle\Twig\FormThemeExtension
    tags:
      - { name: twig.extension }

  ss6.twig.honey_pot_extension:
    class: Shopsys\ShopBundle\Twig\HoneyPotExtension
    tags:
      - { name: twig.extension }

  ss6.twig.image_extension:
    class: Shopsys\ShopBundle\Twig\ImageExtension
    arguments: [%ss6.front_design_image_url_prefix%]
    tags:
      - { name: twig.extension }

  ss6.twig.javascript_extension:
    class: Shopsys\ShopBundle\Twig\Javascript\JavascriptExtension
    tags:
      - { name: twig.extension }

  ss6.twig.localization_extension:
    class: Shopsys\ShopBundle\Twig\LocalizationExtension
    tags:
      - { name: twig.extension }

  ss6.twig.mailer_setting_extension:
    class: Shopsys\ShopBundle\Twig\MailerSettingExtension
    tags:
      - { name: twig.extension }

  ss6.twig.module_extension:
    class: Shopsys\ShopBundle\Twig\ModuleExtension
    tags:
      - { name: twig.extension }

  ss6.twig.number_formatter_extension:
    class: Shopsys\ShopBundle\Twig\NumberFormatterExtension
    tags:
      - { name: twig.extension }

  ss6.twig.input_price_label_extension:
    class: Shopsys\ShopBundle\Twig\InputPriceLabelExtension
    tags:
      - { name: twig.extension }

  ss6.twig.price_extension:
    class: Shopsys\ShopBundle\Twig\PriceExtension
    tags:
      - { name: twig.extension }

  ss6.twig.product_extension:
    class: Shopsys\ShopBundle\Twig\ProductExtension
    tags:
      - { name: twig.extension }

  ss6.twig.product_visibility_extension:
    class: Shopsys\ShopBundle\Twig\ProductVisibilityExtension
    tags:
      - { name: twig.extension }

  ss6.twig.request_extension:
    class: Shopsys\ShopBundle\Twig\RequestExtension
    tags:
      - { name: twig.extension }

  ss6.twig.router_extension:
    class: Shopsys\ShopBundle\Twig\RouterExtension
    tags:
      - { name: twig.extension }

  ss6.twig.seo_extension:
    class: Shopsys\ShopBundle\Twig\SeoExtension
    tags:
      - { name: twig.extension }

  ss6.twig.shop_info_extension:
    class: Shopsys\ShopBundle\Twig\ShopInfoExtension
    tags:
      - { name: twig.extension }

  ss6.twig.var_dumper_extension:
    class: Shopsys\ShopBundle\Twig\VarDumperExtension
    tags:
      - { name: twig.extension }
