parameters:
  ss6.core.security.login_service.class: SS6\CoreBundle\Model\Security\Service\LoginService

services:
  ss6.core.security.login_service:
    class: %ss6.core.security.login_service.class%
