parameters:
  ss6.core.administrator.administrator_repository.class: SS6\CoreBundle\Model\Administrator\Repository\AdministratorRepository
  ss6.core.security.login_listener.class: SS6\CoreBundle\Model\Security\Listener\LoginListener
  ss6.core.security.login_service.class: SS6\CoreBundle\Model\Security\Service\LoginService

services:
  ss6.core.administrator.administrator_repository:
    class: %ss6.core.administrator.administrator_repository.class%
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ["NDShopSys6Bundle:Identities\Identity"]
  
  ss6.core.security.login_listener:
    class: %ss6.core.security.login_listener.class%
    arguments: ["@doctrine.orm.entity_manager"]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
  ss6.core.security.login_service:
    class: %ss6.core.security.login_service.class%
