# specific development configuration

assetic:
  use_controller: false

doctrine:
  orm:
    auto_generate_proxy_classes: true
    metadata_cache_driver: array
    query_cache_driver: array

monolog:
  handlers:
    main:
      type: rotating_file
      max_files: 7
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
    # configuration is merged (not overriden) so "nested" handler must be disabled explicitly
    nested:
      type: "null"
    console:
      type: console
      bubble: false
#    doctrine:
#      action_level: debug
#      type:  stream
#      path:  %kernel.logs_dir%/%kernel.environment%_doctrine.log
#      channels: doctrine

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler:
    enabled: true
    collect: true
    only_exceptions: false
    only_master_requests: true

#swiftmailer:
#    delivery_address: me@example.com

web_profiler:
  toolbar: true
  intercept_redirects: false
