assetic:
  use_controller: false

doctrine:
  dbal:
    host: "%test_database_host%"
    port: "%test_database_port%"
    dbname: "%test_database_name%"
    user: "%test_database_user%"
    password: "%test_database_password%"

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: true
  profiler:
    only_exceptions: false
    only_master_requests: true
  test: ~
  session:
    storage_id: session.storage.mock_file
  profiler:
    collect: false

security:
  firewalls:
    administration:
      http_basic: ~
    frontend:
      http_basic: ~

swiftmailer:
  transport: "%test_mailer_transport%"
  host: "%test_mailer_host%"
  username: "%test_mailer_user%"
  password: "%test_mailer_password%"

web_profiler:
  toolbar: false
  intercept_redirects: false
