doctrine:
  dbal:
    host: "%test_database_host%"
    port: "%test_database_port%"
    dbname: "%test_database_name%"
    user: "%test_database_user%"
    password: "%test_database_password%"

framework:
  test: ~
  session:
    storage_id: session.storage.mock_file
  profiler:
    collect: false
    
swiftmailer:
  transport: "%test_mailer_transport%"
  host: "%test_mailer_host%"
  username: "%test_mailer_user%"
  password: "%test_mailer_password%"

web_profiler:
  toolbar: false
  intercept_redirects: false

swiftmailer:
  disable_delivery: true
