assetic:
  debug: "%kernel.debug%"
  use_controller: false
  bundles: [FMElfinderBundle]
  filters:
    cssrewrite: ~

doctrine:
  dbal:
    driver: "%database_driver%"
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: UTF8

  orm:
    auto_generate_proxy_classes: false
    dql:
      string_functions:
        collate: SS6\ShopBundle\Component\Doctrine\CollateFunction
        normalize: SS6\ShopBundle\Component\Doctrine\NormalizeFunction
    naming_strategy: doctrine.orm.naming_strategy.underscore
    metadata_cache_driver:
      type: service
      id: ss6.doctrine.cache_driver.metadata_cache
    query_cache_driver:
      type: service
      id: ss6.doctrine.cache_driver.query_cache
    auto_mapping: false
    mappings:
      SS6ShopBundle:
        type: annotation
        dir: %kernel.root_dir%/../src/SS6/ShopBundle/Model
        alias: SS6ShopBundle
        prefix: SS6\ShopBundle\Model
        is_bundle: false
      SS6ShopBundleComponent:
        type: annotation
        dir: %kernel.root_dir%/../src/SS6/ShopBundle/Component
        alias: SS6ShopBundleComponent
        prefix: SS6\ShopBundle\Component
        is_bundle: false
    hydrators:
      GroupedScalarHydrator: \SS6\ShopBundle\Component\Doctrine\GroupedScalarHydrator

doctrine_migrations:
    dir_name: "%kernel.root_dir%/../src/SS6/ShopBundle/Migrations"
    namespace: SS6\ShopBundle\Migrations
    table_name: migrations
    name: Migrations

framework:
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: true
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale: "%locale%"
  trusted_hosts: ~
  trusted_proxies: [127.0.0.1]
  session:
    handler_id: ~
    cookie_httponly: true
  fragments: ~
  http_method_override: true
  translator: ~
  profiler:
    enabled: false
    collect: false

monolog:
  channels: ["cron", "slow"]
  handlers:
    main:
      type: fingers_crossed
      buffer_size: 1000
      action_level: warning
      handler: nested
      excluded_404s:
        - ^/
    nested:
      type: rotating_file
      max_files: 7
      path: "%kernel.logs_dir%/%kernel.environment%.log"
      level: debug
      channels: ["!cron", "!slow"]
    cron:
      type: rotating_file
      max_files: 7
      path: "%kernel.logs_dir%/%kernel.environment%.cron.log"
      channels: cron
    slow:
      type: rotating_file
      max_files: 7
      path: "%kernel.logs_dir%/%kernel.environment%.slow.log"
      channels: slow
    cron_console:
      type: console
      verbosity_levels:
        VERBOSITY_NORMAL: INFO
        VERBOSITY_VERBOSE: DEBUG
      channels: cron
      bubble: false
    console:
      type: console

presta_sitemap:
  route_annotation_listener: false

prezent_doctrine_translatable:
  # do not use fallback locale
  # (currentLocale of entities should be set by request or stay NULL)
  fallback_locale: ~

ss6_shop:
  router:
    locale_router_filepaths:
      cs: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/routing_front_cs.yml
      en: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/routing_front_en.yml
    friendly_url_router_filepath: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/routing_friendly_url.yml

stof_doctrine_extensions:
  orm:
    default:
      sortable: true
      tree: true

swiftmailer:
  transport: "%mailer_transport%"
  host: "%mailer_host%"
  username: "%mailer_user%"
  password: "%mailer_password%"
  spool: { type: memory }
  disable_delivery: "%mailer_disable_delivery%"
  delivery_address: "%mailer_master_email_address%"
  delivery_whitelist: "%mailer_delivery_whitelist%"

twig:
  debug: "%kernel.debug%"
  exception_controller: 'SS6\ShopBundle\Controller\Front\ErrorController::showAction'
  form:
    resources:
      - '@SS6Shop/Common/Form/theme.html.twig'
      - '@SS6Shop/Admin/Form/colorpickerFields.html.twig'
      - '@SS6Shop/Admin/Form/fileuploadFields.html.twig'
  strict_variables: true
  globals:
    globalMultipleFormSetting: @ss6.shop.component.form.multiple_form_setting

imports:
    - { resource: wysiwyg.yml }
