framework:
  secret: "%secret%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  templating:
    engines: ['twig']
  default_locale: "%locale%"
  trusted_hosts: ~
  trusted_proxies: ~
  session:
    handler_id: ~
  fragments: ~
  http_method_override: true
  translator: ~

# Twig Configuration
twig:
  debug: "%kernel.debug%"
  exception_controller: 'SS6\ShopBundle\Controller\Front\ErrorController::showAction'
  form:
    resources:
      - '@SS6Shop/Common/Form/fileuploadFields.html.twig'
      - '@SS6Shop/Common/Form/theme.html.twig'
      - '@SS6Shop/Admin/Form/datepickerFields.html.twig'
      - '@SS6Shop/Admin/Form/colorpickerFields.html.twig'
  strict_variables: "%kernel.debug%"
  globals:
    globalMultipleFormSetting: @ss6.shop.form.multiple_form_setting

# Assetic Configuration
assetic:
  debug: "%kernel.debug%"
  use_controller: false
  bundles: [FMElfinderBundle]
  filters:
    cssrewrite: ~

# Doctrine Configuration
doctrine:
  dbal:
    driver: "%database_driver%"
    host: "%database_host%"
    port: "%database_port%"
    dbname: "%database_name%"
    user: "%database_user%"
    password: "%database_password%"
    charset: UTF8

  orm:
    auto_generate_proxy_classes: "%kernel.debug%"
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: false
    mappings:
      SS6ShopBundle:
        type: annotation
        dir: %kernel.root_dir%/../src/SS6/ShopBundle/Model
        alias: SS6ShopBundle
        prefix: SS6\ShopBundle\Model
        is_bundle: false
      SS6ShopBundleComponent:
        type: annotation
        dir: %kernel.root_dir%/../src/SS6/ShopBundle/Component
        alias: SS6ShopBundleComponent
        prefix: SS6\ShopBundle\Component
        is_bundle: false
      SS6ShopBundleTests:
        type: annotation
        dir: %kernel.root_dir%/../src/SS6/ShopBundle/Tests
        alias: SS6ShopBundleTests
        prefix: SS6\ShopBundle\Tests
        is_bundle: false
    hydrators:
      GroupedScalarHydrator: \SS6\ShopBundle\Component\GroupedScalarHydrator

# Swiftmailer Configuration
swiftmailer:
  transport: "%mailer_transport%"
  host: "%mailer_host%"
  username: "%mailer_user%"
  password: "%mailer_password%"
  spool: { type: memory }

ss6_shop:
  router:
    locale_routers:
      cs: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/routing_front_cs.yml
      en: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/routing_front_en.yml

stof_doctrine_extensions:
  orm:
    default:
      tree: true

imports:
    - { resource: wysiwyg.yml }
