ss6_shop:
  resource: "@ShopsysShopBundle/Resources/config/routing.yml"
  prefix: /
  
elfinder:
  resource: "@FMElfinderBundle/Resources/config/routing.yml"
  
fp_js_form_validator:
  resource: "@FpJsFormValidatorBundle/Resources/config/routing.xml"
  prefix: /fp_js_form_validator
