security:
  encoders:
    Symfony\Component\Security\Core\User\UserInterface:
      algorithm: bcrypt
      cost: 12

  role_hierarchy:
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]

  providers:
    administrators:
      entity: 
        class: SS6ShopBundle:Administrator\Administrator

  firewalls:
    administration:
      pattern: ^/admin/
      anonymous: ~
      provider: administrators
      form_login:
        check_path: admin_login_check
        login_path: admin_login
        default_target_path: admin_homepage
        use_referer: true
        username_parameter: "admin_login[username]"
        password_parameter: "admin_login[password]"
        csrf_parameter: "admin_login[_token]"
      logout:
        path: admin_logout
        target: admin_login

  access_control:
    - { path: ^/admin/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, roles: ROLE_ADMIN }