ivory_ck_editor:
  default_config: default
  configs:
    default:
      entities_greek: false
      entities_latin: false
      enterMode: 2
      shiftEnterMode: 1
      shiftEnterMode:
      filebrowserBrowseRoute: elfinder
      toolbar:
        - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
        - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
        - ['Outdent', 'Indent', '-', 'Blockquote']
        - ['Link', 'Unlink']
        - '/'
        - ['Source', '-', 'Image', 'Flash', 'Table', 'SpecialChar', 'Iframe']
        - ['Format']
        - ['FontSize']
        - ['TextColor']

    email:
      entities_greek: false
      entities_latin: false
      enterMode: 2
      shiftEnterMode: 1
      filebrowserBrowseRoute: elfinder
      toolbar:
        - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
        - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
        - ['Outdent', 'Indent', '-', 'Blockquote']
        - ['Link', 'Unlink']
        - '/'
        - ['Source', '-', 'Image', 'SpecialChar']
        - ['Format']
        - ['FontSize']
        - ['TextColor']

fm_elfinder:
  assets_path: /components
  instances:
    default:
      editor: ckeditor
      relative_path: false
      connector:
        roots:
          uploads:
            driver: LocalFileSystem
            path: %shopsys.filemanager_upload_web_dir%
            # show_hidden must be true if access_control is set
            show_hidden: true
            access_control: 'Shopsys\ShopBundle\Model\Security\Filesystem\FilemanagerAccess::isPathAccessibleStatic'