ivory_ck_editor:
  default_config: default
  configs:
    default:
      contentsCss:
        - assets/admin/styles/wysiwyg.css
      filebrowserBrowseRoute: elfinder
      toolbar: 
        - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
        - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
        - ['Outdent', 'Indent', '-', 'Blockquote']
        - ['Link', 'Unlink']
        - '/'
        - ['Source', '-', 'Image', 'Flash', 'Table', 'SpecialChar', 'Iframe']
        - ['Format']
        - ['FontSize']
        - ['TextColor']
    
    email:
      contentsCss:
        - assets/admin/styles/wysiwyg.css
      filebrowserBrowseRoute: elfinder
      toolbar: 
        - ['Bold', 'Italic', 'Underline', 'Strike', 'Superscript', 'Subscript', '-', 'RemoveFormat']
        - ['PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']
        - ['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']
        - ['Outdent', 'Indent', '-', 'Blockquote']
        - ['Link', 'Unlink']
        - '/'
        - ['Source', '-', 'Image', 'SpecialChar']
        - ['Format']
        - ['FontSize']
        - ['TextColor']

fm_elfinder:
  editor: ckeditor
  connector:
    roots:
      uploads:
        driver: LocalFileSystem
        path: assets/uploads