front_cart:
  pattern: /kosik/
  defaults: { _controller: ShopsysShopBundle:Front\Cart:index }

front_customer_edit:
  pattern: /zakaznik/upravit-udaje/
  defaults: { _controller: ShopsysShopBundle:Front\Customer:edit }

front_customer_orders:
  pattern: /zakaznik/objednavky/
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orders }

front_customer_order_detail_registered:
  pattern: /zakaznik/detail-objednavky/{orderNumber}
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailRegistered }

front_customer_order_detail_unregistered:
  pattern: /detail-objednavky/{urlHash}
  defaults: { _controller: ShopsysShopBundle:Front\Customer:orderDetailUnregistered }

front_login:
  pattern: /prihlaseni/
  defaults: { _controller: ShopsysShopBundle:Front\Login:login }

front_logout:
  pattern: /odhlasit/
  # controller's action is unnecessary, because firewall processes whole request

front_order_index:
  pattern: /objednavka/
  defaults: { _controller: ShopsysShopBundle:Front\Order:index }

front_order_sent:
  pattern: /potvrzeni-objednavky/
  defaults: { _controller: ShopsysShopBundle:Front\Order:sent }

front_product_search:
  pattern: /hledani
  defaults: { _controller: ShopsysShopBundle:Front\Product:search }

front_registration_register:
  pattern: /registrace/
  defaults: { _controller: ShopsysShopBundle:Front\Registration:register }

front_registration_reset_password:
  pattern: /zapomenute-heslo/
  defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:resetPassword }

front_registration_set_new_password:
  pattern: /nove-heslo/
  defaults: { _controller: ShopsysShopBundle:Front\CustomerPassword:setNewPassword }

front_brand_list:
  pattern: /prehled-znacek/
  defaults: { _controller: ShopsysShopBundle:Front\Brand:list }
