front_article_detail:
  path: /
  defaults: { _controller: ShopsysShopBundle:Front\Article:detail }

front_product_detail:
  path: /
  defaults: { _controller: ShopsysShopBundle:Front\Product:detail }

front_product_list:
  path: /
  defaults: { _controller: ShopsysShopBundle:Front\Product:listByCategory }

front_brand_detail:
  path: /
  defaults: { _controller: ShopsysShopBundle:Front\Product:listByBrand }
