ss6_shop_front:
  resource: "@ShopsysShopBundle/Resources/config/routing_front.yml"
  prefix: /

ss6_shop_admin:
  resource: "@ShopsysShopBundle/Controller/Admin"
  prefix: /admin
  type: annotation
  defaults:
    _locale: cs