services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Shopsys\ShopBundle\Component\Domain\DomainFactory:
    class: Shopsys\ShopBundle\Component\Domain\DomainFactoryOverwritingDomainUrl
    public: true
    arguments:
      - '%overwrite_domain_url%'
