services:

  ss6.shop.form.admin.customer_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Customer\CustomerFormTypeFactory

  ss6.shop.form.admin.payment.payment_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Payment\PaymentFormTypeFactory

  ss6.shop.form.admin.product.parameter.product_parameter_value_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\Parameter\ProductParameterValueFormTypeFactory

  ss6.shop.form.admin.product.product_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\ProductFormTypeFactory

  ss6.shop.form.admin.slider.slider_item_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Slider\SliderItemFormTypeFactory

  ss6.shop.form.admin.transport.transport_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Transport\TransportFormTypeFactory

  ss6.shop.form.domains:
    class: SS6\ShopBundle\Form\DomainsType
    tags:
      - { name: form.type, alias: domains }

  ss6.shop.form.domain:
    class: SS6\ShopBundle\Form\DomainType
    tags:
      - { name: form.type, alias: domain }

  ss6.shop.form.money:
    class: SS6\ShopBundle\Form\MoneyType
    tags:
      - { name: form.type_extension, alias: money }

  ss6.shop.locale.text:
    class: SS6\ShopBundle\Form\Locale\LocalizedType
    tags:
      - { name: form.type, alias: localized }
