services:

  ss6.shop.form.admin.payment.payment_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Payment\PaymentFormTypeFactory

  ss6.shop.form.admin.product.product_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\ProductFormTypeFactory
