services:

  ss6.shop.form.admin.customer_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Customer\CustomerFormTypeFactory

  ss6.shop.form.admin.payment.payment_edit_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Payment\PaymentEditFormTypeFactory

  ss6.shop.form.admin.payment.payment_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Payment\PaymentFormTypeFactory

  ss6.shop.form.admin.product.parameter.product_parameter_value_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\Parameter\ProductParameterValueFormTypeFactory

  ss6.shop.form.admin.product.product_edit_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\ProductEditFormTypeFactory

  ss6.shop.form.admin.product.product_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Product\ProductFormTypeFactory

  ss6.shop.form.admin.slider.slider_item_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Slider\SliderItemFormTypeFactory

  ss6.shop.form.admin.transport.transport_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Transport\TransportFormTypeFactory

  ss6.shop.form.admin.transport.transport_edit_form_type_factory:
    class: SS6\ShopBundle\Form\Admin\Transport\TransportEditFormTypeFactory

  ss6.shop.form.collection:
    class: SS6\ShopBundle\Form\CollectionType
    tags:
      - { name: form.type_extension, alias: collection }

  ss6.shop.form.color_picker:
    class: SS6\ShopBundle\Form\ColorPickerType
    tags:
      - { name: form.type, alias: color_picker }

  ss6.shop.form.date_picker:
    class: SS6\ShopBundle\Form\DatePickerType
    tags:
      - { name: form.type, alias: date_picker }

  ss6.shop.form.domains:
    class: SS6\ShopBundle\Form\DomainsType
    tags:
      - { name: form.type, alias: domains }

  ss6.shop.form.domain:
    class: SS6\ShopBundle\Form\DomainType
    tags:
      - { name: form.type, alias: domain }

  ss6.shop.form.file_upload:
    class: SS6\ShopBundle\Form\FileUploadType
    tags:
      - { name: form.type, alias: file_upload }

  ss6.shop.form.front.product.product_filter_form_type_factory:
    class: SS6\ShopBundle\Form\Front\Product\ProductFilterFormTypeFactory

  ss6.shop.form.locale.text:
    class: SS6\ShopBundle\Form\Locale\LocalizedType
    tags:
      - { name: form.type, alias: localized }

  ss6.shop.form.money:
    class: SS6\ShopBundle\Form\MoneyType
    tags:
      - { name: form.type_extension, alias: money }

  ss6.shop.form.product:
    class: SS6\ShopBundle\Form\ProductType
    tags:
      - { name: form.type, alias: product }

  ss6.shop.form.single_checkbox_choice_type:
    class: SS6\ShopBundle\Form\SingleCheckboxChoiceType
    tags:
      - { name: form.type, alias: single_checkbox_choice }

  ss6.shop.form.yes_no:
    class: SS6\ShopBundle\Form\YesNoType
    tags:
      - { name: form.type, alias: yes_no }
