- label: 'Nástěnka'
  route: admin_default_dashboard

- label: 'Objednávky'
  route: admin_order_list
  items:
    - label: 'Přijaté objednávky'
      route: admin_order_list

- label: 'Zákazníci'
  route: admin_customer_list
  items:
    - label: 'Registrovaní zákazníci'
      route: admin_customer_list

- label: 'Zboží'
  route: admin_product_list
  items:
    - label: 'Katalog zboží'
      route: admin_product_list
      items:
        - label: 'Nové zboží'
          route: admin_product_new
          visible: false
        - label: 'Editace zboží'
          route: admin_product_edit
          visible: false

- label: 'Marketing'
  route: admin_article_list
  items:
    - label: 'Články'
      route: admin_article_list

- label: 'Nastavení'
  route: admin_orderstatus_list
  type: settings
  items:
    - label: 'Stavy objednávek'
      route: admin_orderstatus_list
    - label: 'Dopravy a platby'
      route: admin_transportandpayment_list
    - label: 'Superadmin'
      route: admin_superadmin_index
      items:
        - label: 'Ikonky'
          route: admin_superadmin_icons
          items:
            - label: 'Detail ikony'
              route: admin_superadmin_icondetail
              visible: false
        - label: 'Chybové stránky'
          route: admin_superadmin_errors

