- label: 'Nástěnka'
  route: admin_default_dashboard

- label: 'Objednávky'
  route: admin_order_list
  items:
    - label: 'Přehled objednávek'
      route: admin_order_list
      items:
        - label: 'Editace objednávky'
          route: admin_order_edit
          visible: false

- label: 'Zákazníci'
  route: admin_customer_list
  items:
    - label: 'Registrovaní zákazníci'
      route: admin_customer_list
      items:
        - label: 'Nový zákazník'
          route: admin_customer_new
          visible: false
        - label: 'Editace zákazníka'
          route: admin_customer_edit
          visible: false

- label: 'Zboží'
  route: admin_product_list
  items:
    - label: 'Přehled zboží'
      route: admin_product_list
      items:
        - label: 'Nové zboží'
          route: admin_product_new
          visible: false
        - label: 'Editace zboží'
          route: admin_product_edit
          visible: false

- label: 'Cenotvorba'
  route: admin_pricinggroup_list
  items:
    - label: 'Cenové skupiny'
      route: admin_pricinggroup_list

    - label: 'DPH a zaokrouhlování'
      route: admin_vat_list

- label: 'Marketing'
  route: admin_article_list
  items:
    - label: 'Přehled článků'
      route: admin_article_list
      items:
        - label: 'Nový článek'
          route: admin_article_new
          visible: false
        - label: 'Editace článku'
          route: admin_article_edit
          visible: false
    - label: 'Slider na titulce'
      route: admin_slider_list
      items:
        - label: 'Nová stránka'
          route: admin_slider_new
          visible: false
        - label: 'Editace stránky'
          route: admin_slider_edit
          visible: false

- label: 'Nastavení'
  route: admin_overview_list
  type: settings
  items:
    - label: 'Identifikace e-shopu'
      route: admin_overview_list

    - label: 'Dopravy a platby'
      route: admin_transportandpayment_list
      items:
        - label: 'Nová doprava'
          route: admin_transport_new
          visible: false
        - label: 'Editace dopravy'
          route: admin_transport_edit
          visible: false
        - label: 'Nová platba'
          route: admin_payment_new
          visible: false
        - label: 'Editace platby'
          route: admin_payment_edit
          visible: false

    - label: 'Komunikace se zákazníkem'
      route: admin_customercommunication_index
      items:
        - label: 'Nastavení emailů'
          route: admin_mail_setting

        - label: 'Šablony emailů'
          route: admin_mail_template

        - label: 'Stránka s potvrzením objednávky'
          route: admin_customercommunication_ordersubmitted

    - label: 'Seznamy a číselníky'
      route: admin_availability_list
      items:
        - label: 'Dostupnost'
          route: admin_availability_list

        - label: 'Parametry'
          route: admin_parameter_list

        - label: 'Stavy objednávek'
          route: admin_orderstatus_list
          items:
            - label: 'Editace stavu objednávek'
              route: admin_orderstatus_edit
              visible: false
            - label: 'Nový stav objednávek'
              route: admin_orderstatus_new
              visible: false

    - label: 'Překlady'
      route: admin_translation_list
      items:
        - label: 'Překlady konstant'
          route: admin_translation_list

        - label: 'URL adresy'
          route: admin_superadmin_urls

    - label: 'Superadmin'
      route: admin_superadmin_index
      items:
        - label: 'Ikonky'
          route: admin_superadmin_icons
          items:
            - label: 'Detail ikony'
              route: admin_superadmin_icondetail
              visible: false
        - label: 'Chybové hlášky'
          route: admin_superadmin_errors
        - label: 'Nastavení prodeje s/bez DPH'
          route: admin_superadmin_pricing
