- service: SS6\ShopBundle\Model\Product\Pricing\ProductPriceCronService
  time:
    minutes: '*'
    hours: '*'

- service: SS6\ShopBundle\Model\Product\Availability\ProductAvailabilityCronService
  time:
    minutes: '*'
    hours: '*'