- service: SS6\ShopBundle\Model\Pricing\Vat\VatDeletionCronService
  time:
    minutes: '*'
    hours: '*'

- service: SS6\ShopBundle\Model\Product\Pricing\ProductPriceCronService
  time:
    minutes: '*'
    hours: '*'

- service: SS6\ShopBundle\Model\Product\ProductVisibilityImmediateCronService
  time:
    minutes: '*'
    hours: '*'

- service: SS6\ShopBundle\Model\Product\ProductVisibilityMidnightCronService
  time:
    minutes: '0'
    hours: '0'

- service: SS6\ShopBundle\Model\Product\Availability\ProductAvailabilityCronService
  time:
    minutes: '*'
    hours: '*'