- name: product
  class: SS6\ShopBundle\Model\Product\Product
  types:
    - name: gallery
      sizes:
        - { name: origin, width: ~, height: ~, crop: false }
        - { name: detail, width: 200, height: 300, crop: false }
        - { name: list, width: 100, height: 100, crop: true }
      
- name: transport
  class: SS6\ShopBundle\Model\Transport\Transport
  sizes:
    - { name: ~, width: 50, height: 50, crop: false }
      
      