# Example:
#- name: product
#  class: SS6\ShopBundle\Model\Product\Product
#  types:
#    - name: gallery
#      filename_method: getGalleryFilename
#      sizes:
#        - { name: origin, width: ~, height: ~, crop: false }
#        - { name: detail, width: 200, height: 300, crop: false }
#        - { name: list, width: 100, height: 100, crop: true }
#    - name: main
#      filename_method: getMainImageFilename
#      sizes:
#        - { name: origin, width: ~, height: ~, crop: false }
#        - { name: detail, width: 200, height: 300, crop: false }

- name: payment
  class: SS6\ShopBundle\Model\Payment\Payment
  filename_method: getImageFilename
  sizes:
    - { name: ~, width: ~, height: ~, crop: false }
      
- name: product
  class: SS6\ShopBundle\Model\Product\Product
  filename_method: getImageFilename
  sizes:
    - { name: origin, width: ~, height: ~, crop: false }
    - { name: default, width: 200, height: 300, crop: false }
    - { name: list, width: 100, height: 100, crop: true }

- name: sliderItem
  class: SS6\ShopBundle\Model\Slider\SliderItem
  filename_method: getImageFilename
  sizes:
    - { name: ~, width: ~, height: ~, crop: false }

- name: transport
  class: SS6\ShopBundle\Model\Transport\Transport
  filename_method: getImageFilename
  sizes:
    - { name: ~, width: ~, height: ~, crop: false }
