front_homepage:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Default:index }

front_product_detail:
  pattern: /product/detail/{id}
  defaults: { _controller: SS6ShopBundle:Front\Product:detail }
  requirements:
    id: \d+

front_product_list:
  pattern: /product/list/
  defaults: { _controller: SS6ShopBundle:Front\Product:list }