front_cart_add_product:
  pattern: /cart/addProduct/
  defaults: { _controller: SS6ShopBundle:Front\Cart:addProduct }
  methods: [POST]

front_cart_add_product_ajax:
  pattern: /cart/addProductAjax/
  defaults: { _controller: SS6ShopBundle:Front\Cart:addProductAjax }
  methods: [POST]

front_cart_box:
  pattern: /cart/box/
  defaults: { _controller: SS6ShopBundle:Front\Cart:box }

front_cart_delete:
  pattern: /cart/delete/{cartItemId}/
  defaults: { _controller: SS6ShopBundle:Front\Cart:delete }
  requirements:
    cartItemId: \d+

front_contact_form_send:
  pattern: /contactForm/
  defaults: { _controller: SS6ShopBundle:Front\ContactForm:send }
  methods: [POST]
  condition: "request.isXmlHttpRequest()"

front_customer_login_as_remembered_user:
  # same pattern must be in security.yml
  pattern: /login-as-remembered-user/
  defaults: { _controller: SS6ShopBundle:Front\Customer:loginAsRememberedUser}

front_homepage:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Default:index }

front_image:
  pattern: /assets/content/images/{entityName}/{type}/{sizeName}/{imageId}.{extension}
  defaults: { _controller: SS6ShopBundle:Front\Image:getImage }
  requirements:
    imageId: \d+

front_image_without_type:
  pattern: /assets/content/images/{entityName}/{sizeName}/{imageId}.{extension}
  defaults:
    _controller: SS6ShopBundle:Front\Image:getImage
    type: ~
  requirements:
    imageId: \d+

front_login_check:
  pattern: /login/check/
  # controller's action is unnecessary, because firewall processes whole request

front_order_save_form:
  pattern: /order/save-form/
  defaults: { _controller: SS6ShopBundle:Front\Order:saveOrderForm }
  methods: [POST]

front_search_autocomplete:
  pattern: /search/autocomplete/
  defaults: { _controller: SS6ShopBundle:Front\Search:autocomplete }
  methods: [POST]
