front_article_detail:
  pattern: /clanek/{id}/
  defaults: { _controller: SS6ShopBundle:Front\Article:detail }
  requirements:
    id: \d+

front_cart:
  pattern: /kosik/
  defaults: { _controller: SS6ShopBundle:Front\Cart:index }

front_customer_edit:
  pattern: /zakaznik/upravit-udaje/
  defaults: { _controller: SS6ShopBundle:Front\Customer:edit }

front_customer_orders:
  pattern: /zakaznik/objednavky/
  defaults: { _controller: SS6ShopBundle:Front\Customer:orders }

front_customer_order_detail_registered:
  pattern: /zakaznik/detail-objednavky/{orderNumber}
  defaults: { _controller: SS6ShopBundle:Front\Customer:orderDetailRegistered }
  requirements:
    cartItemId: \d+

front_customer_order_detail_unregistered:
  pattern: /detail-objednavky/{urlHash}
  defaults: { _controller: SS6ShopBundle:Front\Customer:orderDetailUnregistered }
  requirements:
    cartItemId: \d+

front_login:
  pattern: /prihlaseni/
  defaults: { _controller: SS6ShopBundle:Front\Login:login }

front_logout:
  pattern: /odhlasit/
  # controller's action is unnecessary, because firewall processes whole request

front_order_index:
  pattern: /objednavka/
  defaults: { _controller: SS6ShopBundle:Front\Order:index }

front_order_sent:
  pattern: /potvrzeni-objednavky/
  defaults: { _controller: SS6ShopBundle:Front\Order:sent }

front_product_category:
  pattern: /produkty/kategorie/{categoryId}/{page}
  defaults: {_controller: SS6ShopBundle:Front\Product:listByCategory, page: 1 }
  requirements:
    id: \d+

front_product_search:
  pattern: /hledani/{page}
  defaults: { _controller: SS6ShopBundle:Front\Product:search, page: 1 }

front_registration_register:
  pattern: /registrace/
  defaults: { _controller: SS6ShopBundle:Front\Registration:register }

front_registration_reset_password:
  pattern: /zapomenute-heslo/
  defaults: { _controller: SS6ShopBundle:Front\Registration:resetPassword }

front_registration_set_new_password:
  pattern: /nove-heslo/
  defaults: { _controller: SS6ShopBundle:Front\Registration:setNewPassword }