front_cart_add_product:
  pattern: /cart/addProduct/
  defaults: { _controller: SS6ShopBundle:Front\Cart:addProduct }

front_cart_box:
  pattern: /cart/box/
  defaults: { _controller: SS6ShopBundle:Front\Cart:box }

front_cart_delete:
  pattern: /cart/delete/{cartItemId}/
  defaults: { _controller: SS6ShopBundle:Front\Cart:delete }
  requirements:
    cartItemId: \d+

front_homepage:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Default:index }

front_login_check:
  pattern: /login/check/
  # controller's action is unnecessary, because firewall processes whole request

front_order_save_form:
  pattern: /order/save-form/
  defaults: { _controller: SS6ShopBundle:Front\Order:saveOrderForm }
  methods: [POST]
