front_cart_add_product:
  pattern: /cart/addProduct/
  defaults: { _controller: SS6ShopBundle:Front\Cart:addProduct }
  
front_cart_box:
  pattern: /cart/box/
  defaults: { _controller: SS6ShopBundle:Front\Cart:box }

front_basket_index:
  pattern: /basket/
  defaults: { _controller: SS6ShopBundle:Front\Basket:index }

front_homepage:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Default:index }

front_order_index:
  pattern: /order/
  defaults: { _controller: SS6ShopBundle:Front\Order:index }

front_order_personal:
  pattern: /order/personal/
  defaults: { _controller: SS6ShopBundle:Front\Order:personal }

front_order_sended:
  pattern: /order/sended/
  defaults: { _controller: SS6ShopBundle:Front\Order:sended }

front_product_detail:
  pattern: /product/detail/{id}
  defaults: { _controller: SS6ShopBundle:Front\Product:detail }
  requirements:
    id: \d+
    
front_login:
  pattern: /login/
  defaults: { _controller: SS6ShopBundle:Front\Login:login }
  
front_login_check:
  pattern: /login/check/
  # controller's action is unnecessary, because firewall processes whole request 

front_logout:
  pattern: /logout/
  # controller's action is unnecessary, because firewall processes whole request 
  
front_product_list:
  pattern: /product/list/
  defaults: { _controller: SS6ShopBundle:Front\Product:list }
