front_article_detail:
  pattern: /article/detail/{id}/
  defaults: { _controller: SS6ShopBundle:Front\Article:detail }
  requirements:
    id: \d+

front_cart:
  pattern: /kosik/
  defaults: { _controller: SS6ShopBundle:Front\Cart:index }

front_cart_add_product:
  pattern: /cart/addProduct/
  defaults: { _controller: SS6ShopBundle:Front\Cart:addProduct }
  
front_cart_box:
  pattern: /cart/box/
  defaults: { _controller: SS6ShopBundle:Front\Cart:box }
  
front_cart_delete:
  pattern: /cart/delete/{cartItemId}/
  defaults: { _controller: SS6ShopBundle:Front\Cart:delete }
  requirements:
    cartItemId: \d+

front_customer_edit:
  pattern: /customer/edit/
  defaults: { _controller: SS6ShopBundle:Front\Customer:edit }

front_homepage:
  pattern: /
  defaults: { _controller: SS6ShopBundle:Front\Default:index }

front_login:
  pattern: /login/
  defaults: { _controller: SS6ShopBundle:Front\Login:login }

front_login_check:
  pattern: /login/check/
  # controller's action is unnecessary, because firewall processes whole request

front_logout:
  pattern: /logout/
  # controller's action is unnecessary, because firewall processes whole request 

front_order_index:
  pattern: /objednavka/
  defaults: { _controller: SS6ShopBundle:Front\Order:index }
  
front_order_save_form:
  pattern: /order/save-form/
  defaults: { _controller: SS6ShopBundle:Front\Order:saveOrderForm }
  methods: [POST]

front_order_sent:
  pattern: /potvrzeni-objednavky/
  defaults: { _controller: SS6ShopBundle:Front\Order:sent }

front_product_detail:
  pattern: /product/detail/{id}
  defaults: { _controller: SS6ShopBundle:Front\Product:detail }
  requirements:
    id: \d+
  
front_product_list:
  pattern: /product/list/
  defaults: { _controller: SS6ShopBundle:Front\Product:list }

front_registration_register:
  pattern: /registration/
  defaults: { _controller: SS6ShopBundle:Front\Registration:register }