imports:
  - { resource: ../../Twig/services.yml }

parameters:
  sensio_framework_extra.routing.loader.annot_class.class: SS6\ShopBundle\Component\AnnotatedRouteControllerLoader

services:
  
  doctrine.orm.default_entity_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_class: %doctrine.orm.entity_manager.class%
    factory_method: create
    arguments: 
      - @doctrine.dbal.default_connection
      - @doctrine.orm.default_configuration
  
  doctrine.orm.entity_manager.abstract:
    synthetic: true
    
  ss6.shop.customer.customer_identifier:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifier
    factory_service: ss6.shop.customer.customer_identifier_factory
    factory_method: get
    
  ss6.shop.customer.customer_identifier_factory:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifierFactory

  ss6.shop.product.product_edit_facade:
    class: SS6\ShopBundle\Model\Product\ProductEditFacade
  
  ss6.shop.product.product_repository:
    class: SS6\ShopBundle\Model\Product\ProductRepository
    
  ss6.shop.product.product_visibility_repository:
    class: SS6\ShopBundle\Model\Product\ProductVisibilityRepository
  
  ss6.shop.security.login_listener:
    class: SS6\ShopBundle\Model\Security\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
  ss6.shop.security.login_service:
    class: SS6\ShopBundle\Model\Security\LoginService
    
  ss6.shop.payment.payment_edit_facade:
    class: SS6\ShopBundle\Model\Payment\PaymentEditFacade
    
  ss6.shop.payment.payment_repository:
    class: SS6\ShopBundle\Model\Payment\PaymentRepository

  ss6.shop.transport.transport_edit_facade:
    class: SS6\ShopBundle\Model\Transport\TransportEditFacade

  ss6.shop.transport.transport_repository:
    class: SS6\ShopBundle\Model\Transport\TransportRepository
