imports:
  - { resource: ../../Twig/services.yml }

parameters:
  sensio_framework_extra.routing.loader.annot_class.class: SS6\ShopBundle\Component\AnnotatedRouteControllerLoader
  twig.controller.exception.class: SS6\ShopBundle\Component\ExceptionController

services:
  
  doctrine.orm.default_entity_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_class: %doctrine.orm.entity_manager.class%
    factory_method: create
    arguments: 
      - @doctrine.dbal.default_connection
      - @doctrine.orm.default_configuration
  
  doctrine.orm.entity_manager.abstract:
    synthetic: true

  ss6.shop.article.article_repository:
    class: SS6\ShopBundle\Model\Article\ArticleRepository

  ss6.shop.article.article_edit_facade:
    class: SS6\ShopBundle\Model\Article\ArticleEditFacade

  ss6.shop.cart:
    class: SS6\ShopBundle\Model\Cart\Cart
    factory_service: ss6.shop.cart.cart_singleton_factory
    factory_method: get
    arguments: 
      - @ss6.shop.customer.customer_identifier
    
  ss6.shop.cart.cart_singleton_factory:
    class: SS6\ShopBundle\Model\Cart\CartSingletonFactory
    
  ss6.shop.cart.cart_facade:
    class: SS6\ShopBundle\Model\Cart\CartFacade

  ss6.shop.cart.cart_item_repository:
    class: SS6\ShopBundle\Model\Cart\CartItemRepository

  ss6.shop.cart.cart_service:
    class: SS6\ShopBundle\Model\Cart\CartService

  ss6.shop.customer.customer_identifier:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifier
    factory_service: ss6.shop.customer.customer_identifier_factory
    factory_method: get
    
  ss6.shop.customer.customer_identifier_factory:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifierFactory

  ss6.shop.customer.customer_edit_facade:
    class: SS6\ShopBundle\Model\Customer\CustomerEditFacade

  ss6.shop.customer.registration_service:
    class: SS6\ShopBundle\Model\Customer\RegistrationService

  ss6.shop.customer.user_repository:
    class: SS6\ShopBundle\Model\Customer\UserRepository
    
  ss6.shop.flash_message.admin:
    class: SS6\ShopBundle\Model\FlashMessage\FlashMessage
    arguments: ['admin']
    
  ss6.shop.flash_message.front:
    class: SS6\ShopBundle\Model\FlashMessage\FlashMessage
    arguments: ['front']

  ss6.shop.order.flow:
    class: SS6\ShopBundle\Form\Front\Order\OrderFlow
    parent: craue.form.flow
    scope: request

  ss6.shop.order.order_facade:
    class: SS6\ShopBundle\Model\Order\OrderFacade
    
  ss6.shop.order.order_repository:
    class: SS6\ShopBundle\Model\Order\OrderRepository
    
  ss6.shop.order.order_service:
    class: SS6\ShopBundle\Model\Order\OrderService

  ss6.shop.order.order_repository:
    class: SS6\ShopBundle\Model\Order\OrderRepository

  ss6.shop.order.order_service:
    class: SS6\ShopBundle\Model\Order\OrderService

  ss6.shop.order.order_number_sequence_repository:
    class: SS6\ShopBundle\Model\Order\OrderNumberSequenceRepository

  ss6.shop.payment.payment_edit_facade:
    class: SS6\ShopBundle\Model\Payment\PaymentEditFacade

  ss6.shop.payment.payment_repository:
    class: SS6\ShopBundle\Model\Payment\PaymentRepository

  ss6.shop.product.product_edit_facade:
    class: SS6\ShopBundle\Model\Product\ProductEditFacade
  
  ss6.shop.product.product_repository:
    class: SS6\ShopBundle\Model\Product\ProductRepository
    
  ss6.shop.product.product_visibility_repository:
    class: SS6\ShopBundle\Model\Product\ProductVisibilityRepository
  
  ss6.shop.security.login_listener:
    class: SS6\ShopBundle\Model\Security\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
  ss6.shop.security.login_service:
    class: SS6\ShopBundle\Model\Security\LoginService

  ss6.shop.transport.transport_edit_facade:
    class: SS6\ShopBundle\Model\Transport\TransportEditFacade

  ss6.shop.transport.transport_repository:
    class: SS6\ShopBundle\Model\Transport\TransportRepository
