imports:
  - { resource: ../../Form/services.yml }
  - { resource: ../../Twig/services.yml }

parameters:
  fragment.handler.class: SS6\ShopBundle\Model\SubRequest\RedirectFragmentHandler
  sensio_framework_extra.routing.loader.annot_class.class: SS6\ShopBundle\Component\AnnotatedRouteControllerLoader
  ss6.admin_navigation.config_filepath: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/admin_menu.yml
  ss6.data_fixtures.resources_dir: %kernel.root_dir%/../src/SS6/ShopBundle/DataFixtures/resources/
  ss6.data_fixtures.resource_customers_filepath: %ss6.data_fixtures.resources_dir%/demo-data-customers.csv
  ss6.data_fixtures.resource_products_filepath: %ss6.data_fixtures.resources_dir%/demo-data-products.csv
  ss6.demo_images_archive_url: http://images.mephisto.netdevelo/demoImages.v3.zip
  ss6.demo_images_dql_url: http://images.mephisto.netdevelo/demoImagesDql.v3.dql
  ss6.domain_config_filepath: %kernel.root_dir%/config/domains.yml
  ss6.file_dir: %ss6.web_dir%/assets/content/files
  ss6.file_url_prefix: /assets/content/files/
  ss6.image_dir: %ss6.web_dir%/assets/content/images
  ss6.image_url_prefix: /assets/content/images/
  ss6.image_config_filepath: %kernel.root_dir%/../src/SS6/ShopBundle/Resources/config/images.yml
  ss6.web_dir: %kernel.root_dir%/../web
  twig.controller.exception.class: SS6\ShopBundle\Component\ExceptionController

services:
  
  doctrine.orm.default_entity_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_class: %doctrine.orm.entity_manager.class%
    factory_method: create
    arguments: 
      - @doctrine.dbal.default_connection
      - @doctrine.orm.default_configuration
  
  doctrine.orm.entity_manager.abstract:
    synthetic: true

  security.user.provider.concrete.user_identities:
    class: SS6\ShopBundle\Model\Customer\SecurityUserRepository

  ss6.shop.admin_navigation.breadcrumb:
    class: SS6\ShopBundle\Model\AdminNavigation\Breadcrumb
    factory_service: ss6.shop.admin_navigation.breadcrumb_factory
    factory_method: get

  ss6.shop.admin_navigation.breadcrumb_factory:
    class: SS6\ShopBundle\Model\AdminNavigation\BreadcrumbFactory

  ss6.shop.admin_navigation.menu:
    class: SS6\ShopBundle\Model\AdminNavigation\Menu
    factory_service: ss6.shop.admin_navigation.menu_loader
    factory_method: loadFromYaml
    arguments:
      - %ss6.admin_navigation.config_filepath%

  ss6.shop.admin_navigation.menu_loader:
    class: SS6\ShopBundle\Model\AdminNavigation\MenuLoader
    
  ss6.shop.administrator.administrator_grid_facade:
    class: SS6\ShopBundle\Model\Administrator\AdministratorGridFacade
    
  ss6.shop.administrator.administrator_grid_service:
    class: SS6\ShopBundle\Model\Administrator\AdministratorGridService

  ss6.shop.article.article_edit_facade:
    class: SS6\ShopBundle\Model\Article\ArticleEditFacade

  ss6.shop.article.article_repository:
    class: SS6\ShopBundle\Model\Article\ArticleRepository

  ss6.shop.cart:
    class: SS6\ShopBundle\Model\Cart\Cart
    factory_service: ss6.shop.cart.cart_factory
    factory_method: get
    arguments: 
      - @ss6.shop.customer.customer_identifier
      
  ss6.shop.cart.cart_facade:
    class: SS6\ShopBundle\Model\Cart\CartFacade
    
  ss6.shop.cart.cart_factory:
    class: SS6\ShopBundle\Model\Cart\CartFactory

  ss6.shop.cart.cart_migration_facade:
    class: SS6\ShopBundle\Model\Cart\CartMigrationFacade
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  ss6.shop.cart.cart_service:
    class: SS6\ShopBundle\Model\Cart\CartService

  ss6.shop.cart.cart_summary_calculation:
    class: SS6\ShopBundle\Model\Cart\CartSummaryCalculation

  ss6.shop.cart.cart_watcher_facade:
    class: SS6\ShopBundle\Model\Cart\Watcher\CartWatcherFacade
    arguments:
      - @ss6.shop.flash_message.sender.front

  ss6.shop.cart.cart_watcher_service:
    class: SS6\ShopBundle\Model\Cart\Watcher\CartWatcherService
    arguments:
      - @ss6.shop.flash_message.sender.front

  ss6.shop.cart.item.cart_item_repository:
    class: SS6\ShopBundle\Model\Cart\Item\CartItemRepository

  ss6.shop.cart.item.price_calculation:
    class: SS6\ShopBundle\Model\Cart\Item\PriceCalculation

  ss6.shop.csv.csv_reader:
    class: SS6\ShopBundle\Model\Csv\CsvReader
    
  ss6.shop.customer.customer_identifier:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifier
    factory_service: ss6.shop.customer.customer_identifier_factory
    factory_method: get

  ss6.shop.customer.customer_edit_facade:
    class: SS6\ShopBundle\Model\Customer\CustomerEditFacade

  ss6.shop.customer.customer_edit_service:
    class: SS6\ShopBundle\Model\Customer\CustomerEditService

  ss6.shop.customer.customer_identifier_factory:
    class: SS6\ShopBundle\Model\Customer\CustomerIdentifierFactory

  ss6.shop.customer.registration_service:
    class: SS6\ShopBundle\Model\Customer\RegistrationService

  ss6.shop.customer.user_repository:
    class: SS6\ShopBundle\Model\Customer\UserRepository

  ss6.shop.confirm_delete.confirm_delete_response_factory:
    class: SS6\ShopBundle\Model\ConfirmDelete\ConfirmDeleteResponseFactory

  ss6.shop.data_fixture.persistent_reference_repository:
    class: SS6\ShopBundle\Model\DataFixture\PersistentReferenceRepository

  ss6.shop.data_fixture.persistent_reference_service:
    class: SS6\ShopBundle\Model\DataFixture\PersistentReferenceService

  ss6.shop.data_fixtures.product_data_fixture_loader:
    class: SS6\ShopBundle\DataFixtures\Demo\ProductDataFixtureLoader
    arguments:
      - %ss6.data_fixtures.resource_products_filepath%

  ss6.shop.data_fixtures.user_data_fixture_loader:
    class: SS6\ShopBundle\DataFixtures\Demo\UserDataFixtureLoader
    arguments:
      - %ss6.data_fixtures.resource_customers_filepath%

  ss6.shop.domain:
    class: SS6\ShopBundle\Model\Domain\Domain
    factory_service: ss6.shop.domain.domain_factory
    factory_method: create
    arguments:
      - %ss6.domain_config_filepath%

  ss6.shop.domain.config.domains_config_loader:
    class: SS6\ShopBundle\Model\Domain\Config\DomainsConfigLoader

  ss6.shop.domain.domain_factory:
    class: SS6\ShopBundle\Model\Domain\DomainFactory

  ss6.shop.domain.selected_domain:
    class: SS6\ShopBundle\Model\Domain\SelectedDomain

  ss6.shop.file_upload:
    class: SS6\ShopBundle\Model\FileUpload\FileUpload
    arguments: [%kernel.cache_dir%, %ss6.file_dir%, %ss6.image_dir%]
    
  ss6.shop.file_upload.doctrine_listener:
    class: SS6\ShopBundle\Model\FileUpload\DoctrineListener
    tags:
      - { name: doctrine.event_listener, event: postPersist }
      - { name: doctrine.event_listener, event: postUpdate }
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
      
  ss6.shop.file_upload.file_naming_convention:
    class: SS6\ShopBundle\Model\FileUpload\FileNamingConvention

  ss6.shop.flash_message.bag.admin:
    class: SS6\ShopBundle\Model\FlashMessage\Bag
    arguments: ['admin']

  ss6.shop.flash_message.bag.front:
    class: SS6\ShopBundle\Model\FlashMessage\Bag
    arguments: ['front']

  ss6.shop.flash_message.sender.admin:
    class: SS6\ShopBundle\Model\FlashMessage\FlashMessageSender
    arguments:
      - @ss6.shop.flash_message.bag.admin

  ss6.shop.flash_message.sender.front:
    class: SS6\ShopBundle\Model\FlashMessage\FlashMessageSender
    arguments:
      - @ss6.shop.flash_message.bag.front

  ss6.shop.form.multiple_form_setting:
    class: SS6\ShopBundle\Model\Form\MultipleFormSetting

  ss6.shop.grid.drag_and_drop.grid_ordering_service:
    class: SS6\ShopBundle\Model\Grid\DragAndDrop\GridOrderingService
    arguments:
      - @service_container

  ss6.shop.image.directory_structure_creator:
    class: SS6\ShopBundle\Model\Image\DirectoryStructureCreator
    arguments: [%ss6.image_dir%]

  ss6.shop.image.image_config:
    class: SS6\ShopBundle\Model\Image\Config\ImageConfig
    factory_service: ss6.shop.image.image_config_loader
    factory_method: loadFromYaml
    arguments:
      - %ss6.image_config_filepath%

  ss6.shop.image.image_config_loader:
    class: SS6\ShopBundle\Model\Image\Config\ImageConfigLoader
    
  ss6.shop.image.images_entity:
    class: SS6\ShopBundle\Model\Image\ImagesEntity
    arguments: [%ss6.image_dir%]

  ss6.shop.mail.mail_template_facade:
    class: SS6\ShopBundle\Model\Mail\MailTemplateFacade

  ss6.shop.mail.mail_template_repository:
    class: SS6\ShopBundle\Model\Mail\MailTemplateRepository

  ss6.shop.order.flow:
    class: SS6\ShopBundle\Form\Front\Order\OrderFlow
    parent: craue.form.flow
    scope: request
    
  ss6.shop.order.item.price_calculation:
    class: SS6\ShopBundle\Model\Order\Item\PriceCalculation

  ss6.shop.order.order_facade:
    class: SS6\ShopBundle\Model\Order\OrderFacade

  ss6.shop.order.order_flow_facade:
    class: SS6\ShopBundle\Model\Order\OrderFlowFacade
  
  ss6.shop.order.order_mail_facade:
    class: SS6\ShopBundle\Model\Order\Mail\OrderMailFacade
    arguments: [@mailer]
    
  ss6.shop.order.order_mail_service:
    class: SS6\ShopBundle\Model\Order\Mail\OrderMailService
    arguments: ["%main_email%"]

  ss6.shop.order.order_number_sequence_repository:
    class: SS6\ShopBundle\Model\Order\OrderNumberSequenceRepository

  ss6.shop.order.order_price_calculation:
    class: SS6\ShopBundle\Model\Order\PriceCalculation

  ss6.shop.order.order_repository:
    class: SS6\ShopBundle\Model\Order\OrderRepository

  ss6.shop.order.order_service:
    class: SS6\ShopBundle\Model\Order\OrderService
  
  ss6.shop.order.order_status_facade:
    class: SS6\ShopBundle\Model\Order\Status\OrderStatusFacade

  ss6.shop.order.order_status_mail_template_service:
    class: SS6\ShopBundle\Model\Order\Status\OrderStatusMailTemplateService

  ss6.shop.order.order_status_repository:
    class: SS6\ShopBundle\Model\Order\Status\OrderStatusRepository
    
  ss6.shop.order.order_status_service:
    class: SS6\ShopBundle\Model\Order\Status\OrderStatusService
  
  ss6.shop.order.order_transport_and_payment_watcher_service:
    class: SS6\ShopBundle\Model\Order\Watcher\TransportAndPaymentWatcherService
    arguments:
      - @ss6.shop.flash_message.bag.front

  ss6.shop.order.preview.order_preview_calculation:
    class: SS6\ShopBundle\Model\Order\Preview\OrderPreviewCalculation

  ss6.shop.order.status.grid.order_status_inline_edit:
    class: SS6\ShopBundle\Model\Order\Status\Grid\OrderStatusInlineEdit

  ss6.shop.order.status.grid.order_status_grid_factory:
    class: SS6\ShopBundle\Model\Order\Status\Grid\OrderStatusGridFactory

  ss6.shop.payment.payment_detail_factory:
    class: SS6\ShopBundle\Model\Payment\Detail\Factory

  ss6.shop.payment.payment_edit_facade:
    class: SS6\ShopBundle\Model\Payment\PaymentEditFacade

  ss6.shop.payment.payment_repository:
    class: SS6\ShopBundle\Model\Payment\PaymentRepository

  ss6.shop.payment.price_calculation:
    class: SS6\ShopBundle\Model\Payment\PriceCalculation

  ss6.shop.grid.factory:
    class: SS6\ShopBundle\Model\Grid\GridFactory

  ss6.shop.grid.inline_edit.inline_edit_service:
    class: SS6\ShopBundle\Model\Grid\InlineEdit\InlineEditService
    arguments:
      - @service_container

  ss6.shop.payment.visibility_calculation:
    class: SS6\ShopBundle\Model\Payment\VisibilityCalculation

  ss6.shop.pricing.delayed_pricing_setting:
    class: SS6\ShopBundle\Model\Pricing\DelayedPricingSetting

  ss6.shop.pricing.input_price_calculation:
    class: SS6\ShopBundle\Model\Pricing\InputPriceCalculation

  ss6.shop.pricing.input_price_facade:
    class: SS6\ShopBundle\Model\Pricing\InputPriceFacade
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

  ss6.shop.pricing.input_price_repository:
    class: SS6\ShopBundle\Model\Pricing\InputPriceRepository

  ss6.shop.pricing.price_calculation:
    class: SS6\ShopBundle\Model\Pricing\PriceCalculation

  ss6.shop.pricing.base_price_calculation:
    class: SS6\ShopBundle\Model\Pricing\BasePriceCalculation

  ss6.shop.pricing.pricing_setting:
    class: SS6\ShopBundle\Model\Pricing\PricingSetting

  ss6.shop.pricing.pricing_setting_facade:
    class: SS6\ShopBundle\Model\Pricing\PricingSettingFacade
    
  ss6.shop.pricing.rounding:
    class: SS6\ShopBundle\Model\Pricing\Rounding

  ss6.shop.pricing.vat.vat_facade:
    class: SS6\ShopBundle\Model\Pricing\Vat\VatFacade

  ss6.shop.pricing.vat.vat_grid_factory:
    class: SS6\ShopBundle\Model\Pricing\Vat\VatGridFactory

  ss6.shop.pricing.vat.vat_inline_edit:
    class: SS6\ShopBundle\Model\Pricing\Vat\VatInlineEdit
    
  ss6.shop.pricing.vat.vat_repository:
    class: SS6\ShopBundle\Model\Pricing\Vat\VatRepository
    
  ss6.shop.pricing.vat.vat_service:
    class: SS6\ShopBundle\Model\Pricing\Vat\VatService
    
  ss6.shop.product.availability.availability_inline_edit:
    class: SS6\ShopBundle\Model\Product\Availability\AvailabilityInlineEdit
    
  ss6.shop.product.availability.availability_facade:
    class: SS6\ShopBundle\Model\Product\Availability\AvailabilityFacade

  ss6.shop.product.availability.availability_grid_factory:
    class: SS6\ShopBundle\Model\Product\Availability\AvailabilityGridFactory

  ss6.shop.product.availability.availability_repository:
    class: SS6\ShopBundle\Model\Product\Availability\AvailabilityRepository

  ss6.shop.product.availability.availability_service:
    class: SS6\ShopBundle\Model\Product\Availability\AvailabilityService

  ss6.shop.product.list.product_list_admin_facade:
    class: SS6\ShopBundle\Model\Product\Listing\ProductListAdminFacade
    
  ss6.shop.product.list.product_list_admin_repository:
    class: SS6\ShopBundle\Model\Product\Listing\ProductListAdminRepository
    
  ss6.shop.product.parameter.parameter_inline_edit:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterInlineEdit
    
  ss6.shop.product.parameter.parameter_facade:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterFacade

  ss6.shop.product.parameter.parameter_grid_factory:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterGridFactory

  ss6.shop.product.parameter.parameter_repository:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterRepository

  ss6.shop.product.parameter.parameter_service:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterService

  ss6.shop.product.parameter.parameter_value_to_parameter_text_transformer:
    class: SS6\ShopBundle\Model\Product\Parameter\ParameterValueToParameterTextTransformer

  ss6.shop.product.price_calculation:
    class: SS6\ShopBundle\Model\Product\PriceCalculation

  ss6.shop.product.product_data_factory:
    class: SS6\ShopBundle\Model\Product\ProductDataFactory

  ss6.shop.product.product_detail_factory:
    class: SS6\ShopBundle\Model\Product\Detail\Factory

  ss6.shop.product.product_edit_facade:
    class: SS6\ShopBundle\Model\Product\ProductEditFacade
  
  ss6.shop.product.product_facade:
    class: SS6\ShopBundle\Model\Product\ProductFacade
  
  ss6.shop.product.product_repository:
    class: SS6\ShopBundle\Model\Product\ProductRepository
    
  ss6.shop.product.product_visibility_facade:
    class: SS6\ShopBundle\Model\Product\ProductVisibilityFacade
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    
  ss6.shop.product.product_visibility_repository:
    class: SS6\ShopBundle\Model\Product\ProductVisibilityRepository

  ss6.shop.slider.grid.drag_and_drop_ordering_service:
    class: SS6\ShopBundle\Model\Slider\Grid\DragAndDropOrderingService

  ss6.shop.slider.slider_item_facade:
    class: SS6\ShopBundle\Model\Slider\SliderItemFacade

  ss6.shop.slider.slider_item_repository:
    class: SS6\ShopBundle\Model\Slider\SliderItemRepository

  ss6.shop.sub_request.sub_request_listener:
    class: SS6\ShopBundle\Model\SubRequest\SubRequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

  ss6.shop.security.login_listener:
    class: SS6\ShopBundle\Model\Security\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
  ss6.shop.security.login_service:
    class: SS6\ShopBundle\Model\Security\LoginService

  ss6.shop.security.logout_handler:
    class: SS6\ShopBundle\Model\Security\LogoutHandler

  ss6.shop.setting:
    class: SS6\ShopBundle\Model\Setting\Setting
    
  ss6.shop.setting.setting_value_repository:
    class: SS6\ShopBundle\Model\Setting\SettingValueRepository

  ss6.shop.transport.grid.drag_and_drop_ordering_service:
    class: SS6\ShopBundle\Model\Transport\Grid\DragAndDropOrderingService

  ss6.shop.transport.price_calculation:
    class: SS6\ShopBundle\Model\Transport\PriceCalculation

  ss6.shop.transport.transport_detail_factory:
    class: SS6\ShopBundle\Model\Transport\Detail\Factory

  ss6.shop.transport.transport_edit_facade:
    class: SS6\ShopBundle\Model\Transport\TransportEditFacade

  ss6.shop.transport.transport_repository:
    class: SS6\ShopBundle\Model\Transport\TransportRepository

  ss6.shop.transport.visibility_calculation:
    class: SS6\ShopBundle\Model\Transport\VisibilityCalculation

  twig.stringloader:
    class: Twig_Loader_String
    tags:
      - { name: twig.loader }
