imports:
  - { resource: ../../Twig/services.yml }

services:
  
  doctrine.orm.default_entity_manager:
    class: %doctrine.orm.entity_manager.class%
    factory_class: %doctrine.orm.entity_manager.class%
    factory_method: create
    arguments: 
      - @doctrine.dbal.default_connection
      - @doctrine.orm.default_configuration
  
  doctrine.orm.entity_manager.abstract:
    synthetic: true

  ss6.core.product.product_edit_facade:
    class: SS6\ShopBundle\Model\Product\ProductEditFacade
    
  ss6.core.product.product_edit_service:
    class: SS6\ShopBundle\Model\Product\ProductEditService
  
  ss6.core.product.product_repository:
    class: SS6\ShopBundle\Model\Product\ProductRepository
  
  ss6.core.security.login_listener:
    class: SS6\ShopBundle\Model\Security\LoginListener
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    
  ss6.core.security.login_service:
    class: SS6\ShopBundle\Model\Security\LoginService
    
  ss6.core.payment.payment_edit_facade:
    class: SS6\ShopBundle\Model\Payment\PaymentEditFacade
    
  ss6.core.payment.payment_repository:
    class: SS6\ShopBundle\Model\Payment\PaymentRepository

  ss6.core.transport.transport_edit_facade:
    class: SS6\ShopBundle\Model\Transport\TransportEditFacade

  ss6.core.transport.transport_repository:
    class: SS6\ShopBundle\Model\Transport\TransportRepository
