name: Master composer security check
on:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: bcmath, gd, intl, pdo_pgsql, redis, pgsql, zip
                    tools: composer
            -   run: composer install
            -   run: php ./bin/console security:check
