front_homepage:
  pattern: /
  defaults: { _controller: SS6FrontBundle:Default:index }

front_product_detail:
  pattern: /product/detail/{id}
  defaults: { _controller: SS6FrontBundle:Product:detail }
  requirements:
    id: \d+
